apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: orp-letsencrypt
  namespace: cert-manager #retuired cert-manager (same as cert-manager)
spec:
  acme:
    email: k8s@domain.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: orp-letsencrypt-key
    solvers:
      - http01:
          ingress:
            class:  istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orp-certs
  namespace: istio-system #retuired istio-system (same as ingress-gateway service)
spec:
  dnsNames:
  - auth.domain.com
  - app.domain.com
  secretName: orp-certs-tls
  issuerRef:
    kind: ClusterIssuer
    name: orp-letsencrypt
