apiVersion: v1
kind: Secret
metadata:
  name: cicd-registry-secret
  labels:
    app: registry
  namespace: cicd
type: Opaque
data:
  htpasswd: "Y2ljZDokMnkkMDUkRTN5ZlFCY3ovdVFHcWxnaEE3TEMuT0E4MGlRVWpTQjFRLmhlN09Vd1VEUy9JM0xDdm92NXk="
  # $ htpasswd -Bbn cicd yb9738z
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registrystorage
  labels:
    name: registrystorage # jenkins claim for volume
spec:
  storageClassName: cicdstorage # same storage class as pvc
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.2 # ip addres of nfs server
    path: "/mnt/k8s/nfsroot"  # path to directory, make sure directory is available
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: cicd
spec:
  storageClassName: cicdstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: cicd
spec:
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: cicd
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: auth
        secret:
          secretName: cicd-registry-secret
          items:
          - key: htpasswd
            path: htpasswd

      - name: registry-vol
        persistentVolumeClaim:
          claimName: registry-data

      containers:
        - image: registry:2
          name: registry
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
          ports:
            - containerPort: 5000
          volumeMounts:
          #- name: certs-vol
          #  mountPath: /certs
          - name: registry-vol
            mountPath: /var/lib/registry
            subPath: registry
          - name: auth
            mountPath: /auth
            readOnly: true
