apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cicd-letsencrypt
  namespace: cert-manager #retuired cert-manager (same as cert-manager)
spec:
  acme:
    email: k8s@domain.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cicd-letsencrypt-key
    solvers:
      - http01:
          ingress:
            class:  istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cicd-certs
  namespace: istio-system #retuired istio-system (same as ingress-gateway service)
spec:
  dnsNames:
  - git.domain.com
  - registry.domain.com
  - jenkins.domain.com
  secretName: cicd-certs-tls
  issuerRef:
    kind: ClusterIssuer
    name: cicd-letsencrypt
